### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YuanshengZhao** [YuanshengZhao/Garamond-Math#6]
- [ ] `\geqslant`
- [ ] `\mathcal` (currently, new normal weight(in `temp` folder) needs a lot of calibration, and bold has not been made. Long time needed)
- [ ] optical size (currently interpolation is used. Long time needed)
- [ ] `mathfrak` (current glyphs are from TG Termes. No ideas yet)

**Comment by cluelessnessness** [comment]
What is the plan for `\mathcal`? Is it going to continue to be a Copperplate?

If plans aren’t fixed, I’d suggest making `\mathcal` a calligraphic alphabet again and leaving the Copperplate for `\mathscr`; I think the ability to pick which one to use is helpful when writing mathematics.

**Comment by YuanshengZhao** [comment]
The regular weight has been made (though there are still lots of problems), it is Copperplate but "not that Copperplate". 

In fact, some fonts do distinguish these two (like XITS Math, STIX 2, etc.). It is a nice point to consider.

We may consider having `\mathcal` and `\mathscr` simultainously later on (maybe after getting a almost satisfactory solution to the metric problems which is the main issue at the present).

**Comment by ArchangeGabriel** [comment]
Is this related to lowercase normal letters and mathcal letters being the same (not wanted) while uppercase are different (normal)?
[test.pdf](https://github.com/YuanshengZhao/Garamond-Math/files/5161534/test.pdf)
